
version: 2.1

jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file stackcreation.yml \
              --parameters-file stackcreation.json \
              --stack-name newStackCirle \
              --region us-west-2

workflows:
  my_ workflow:
    jobs:
      - create_infrastructure
